import {Dimensions, StyleSheet} from 'react-native';

const {width: screenWidth} = Dimensions.get('window');
const IMAGE_WIDTH = 200;
const TEXT_WIDTH = screenWidth - IMAGE_WIDTH - 76; // Upewniamy się, że tekst nie jest za szeroki i nie wypycha obraaka
const CARD_WIDTH = screenWidth - 32;
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
  },
  title: {
    fontWeight: 500,
    fontSize: 36,
    marginBottom: 16,
    color: '#162C1B',
    marginTop: 16,
    width: '100%',
  },
  card: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderRadius: 25,
    borderWidth: 1,
    padding: 12,
    paddingLeft: 20,
    backgroundColor: '#F4F6F5',
    zIndex: 1,
    marginTop: 12,
    marginBottom: 12,
    width: CARD_WIDTH,
    marginLeft: 16,
    marginRight: 16,
  },
  label: {
    fontSize: 12,
    fontWeight: 500,
    color: '#59695C',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  text: {
    fontSize: 16,
    letterSpacing: -0.2,
    fontWeight: 400,
    marginBottom: 16,
    maxWidth: TEXT_WIDTH,
  },
  img: {
    width: IMAGE_WIDTH,
    height: 200,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#224229',
  },
  shadowWrapper: {
    position: 'relative',
  },
  shadow: {
    position: 'absolute',
    top: 6,
    left: 6,
    right: -6,
    bottom: -6,
    backgroundColor: '#224229',
    borderRadius: 25,
    zIndex: 0,
    marginTop: 12,
    marginBottom: 12,
    marginLeft: 16,
    marginRight: 16,
  },
  icon: {
    marginRight: 8,
    fontSize: 18,
  },
  input: {
    backgroundColor: 'white',
    marginLeft: 16,
    marginRight: 16,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#162C1B',
    borderRadius: 100,
    paddingLeft: 24,
    paddingTop: 8,
    paddingBottom: 8,
    width: '100%',
  },
  likeButtonContainer: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#224229',
  },
  likeButtonContent: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingRight: 16,
    paddingLeft: 16,
    paddingTop: 8,
    paddingBottom: 8,
  },
  likeButtonText: {
    fontSize: 14,
    fontWeight: 400,
    color: '#224229',
    textTransform: 'uppercase',
    marginLeft: 4,
  },
});
